//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class myEIMSEntity : DbContext
    {
        public myEIMSEntity()
            : base("name=myEIMSEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAssignedTask> tblAssignedTasks { get; set; }
        public virtual DbSet<tblComment> tblComments { get; set; }
        public virtual DbSet<tblInternInfo> tblInternInfoes { get; set; }
        public virtual DbSet<tblMainMenu> tblMainMenus { get; set; }
        public virtual DbSet<tblMentorInfo> tblMentorInfoes { get; set; }
        public virtual DbSet<tblPreference> tblPreferences { get; set; }
        public virtual DbSet<tblProj_Task> tblProj_Task { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSubMenu> tblSubMenus { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<FileDetail> FileDetails { get; set; }
        public virtual DbSet<tblProject> tblProjects { get; set; }
    
        public virtual int AddComment(string comment, Nullable<int> internId, Nullable<System.DateTime> dateTime, Nullable<int> projectId, Nullable<int> weekId)
        {
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddComment", commentParameter, internIdParameter, dateTimeParameter, projectIdParameter, weekIdParameter);
        }
    
        public virtual int AddFileDetails(Nullable<int> internId, string fileName, byte[] fileContent)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var fileNameParameter = fileName != null ?
                new ObjectParameter("FileName", fileName) :
                new ObjectParameter("FileName", typeof(string));
    
            var fileContentParameter = fileContent != null ?
                new ObjectParameter("FileContent", fileContent) :
                new ObjectParameter("FileContent", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddFileDetails", internIdParameter, fileNameParameter, fileContentParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> checkPreferenceSettingsById(Nullable<int> internId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("internId", internId) :
                new ObjectParameter("internId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("checkPreferenceSettingsById", internIdParameter);
        }
    
        public virtual int CreateUser(string username, string password, Nullable<int> roleId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var roleIdParameter = roleId.HasValue ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CreateUser", usernameParameter, passwordParameter, roleIdParameter);
        }
    
        public virtual int DeleteIntern(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteIntern", idParameter);
        }
    
        public virtual int DeleteMentor(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteMentor", idParameter);
        }
    
        public virtual int DeleteProject(Nullable<int> projId)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProject", projIdParameter);
        }
    
        public virtual int DeleteTask(Nullable<int> taskId)
        {
            var taskIdParameter = taskId.HasValue ?
                new ObjectParameter("taskId", taskId) :
                new ObjectParameter("taskId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteTask", taskIdParameter);
        }
    
        public virtual int EditIntern(string internId, string fName, string mName, string lName, string address, string email, string contact, string qualification, Nullable<int> id)
        {
            var internIdParameter = internId != null ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(string));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("Qualification", qualification) :
                new ObjectParameter("Qualification", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditIntern", internIdParameter, fNameParameter, mNameParameter, lNameParameter, addressParameter, emailParameter, contactParameter, qualificationParameter, idParameter);
        }
    
        public virtual int EditMentor(string mentorId, string fName, string mName, string lName, string address, string email, string contact, Nullable<int> id)
        {
            var mentorIdParameter = mentorId != null ?
                new ObjectParameter("MentorId", mentorId) :
                new ObjectParameter("MentorId", typeof(string));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditMentor", mentorIdParameter, fNameParameter, mNameParameter, lNameParameter, addressParameter, emailParameter, contactParameter, idParameter);
        }
    
        public virtual int EditMentortbl(Nullable<int> id, string fName, Nullable<int> projId, string mName, string lName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditMentortbl", idParameter, fNameParameter, projIdParameter, mNameParameter, lNameParameter);
        }
    
        public virtual int EditProject(string projId, string projectName, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var projIdParameter = projId != null ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(string));
    
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EditProject", projIdParameter, projectNameParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int EdittblInternInfo(Nullable<int> projId, Nullable<int> internId, string projRole)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var projRoleParameter = projRole != null ?
                new ObjectParameter("ProjRole", projRole) :
                new ObjectParameter("ProjRole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EdittblInternInfo", projIdParameter, internIdParameter, projRoleParameter);
        }
    
        public virtual ObjectResult<getAllAssignedInternInfo_Result> getAllAssignedInternInfo(Nullable<int> projId)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllAssignedInternInfo_Result>("getAllAssignedInternInfo", projIdParameter);
        }
    
        public virtual ObjectResult<getAllAssignedMentor_Result> getAllAssignedMentor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllAssignedMentor_Result>("getAllAssignedMentor");
        }
    
        public virtual ObjectResult<getAllInternByMentorId_Result> getAllInternByMentorId(Nullable<int> mentorId, Nullable<int> projId)
        {
            var mentorIdParameter = mentorId.HasValue ?
                new ObjectParameter("mentorId", mentorId) :
                new ObjectParameter("mentorId", typeof(int));
    
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllInternByMentorId_Result>("getAllInternByMentorId", mentorIdParameter, projIdParameter);
        }
    
        public virtual ObjectResult<getAllPreferences_Result> getAllPreferences()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllPreferences_Result>("getAllPreferences");
        }
    
        public virtual ObjectResult<getAllProject_Result> getAllProject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getAllProject_Result>("getAllProject");
        }
    
        public virtual ObjectResult<GetAssignedMentorByProjId_Result> GetAssignedMentorByProjId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignedMentorByProjId_Result>("GetAssignedMentorByProjId", idParameter);
        }
    
        public virtual ObjectResult<GetAssignedTaskById_Result> GetAssignedTaskById(Nullable<int> projId, Nullable<int> prefId, Nullable<int> weekId, string assignedBy)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var prefIdParameter = prefId.HasValue ?
                new ObjectParameter("prefId", prefId) :
                new ObjectParameter("prefId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("weekId", weekId) :
                new ObjectParameter("weekId", typeof(int));
    
            var assignedByParameter = assignedBy != null ?
                new ObjectParameter("AssignedBy", assignedBy) :
                new ObjectParameter("AssignedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAssignedTaskById_Result>("GetAssignedTaskById", projIdParameter, prefIdParameter, weekIdParameter, assignedByParameter);
        }
    
        public virtual ObjectResult<getComment_Result> getComment(Nullable<int> mentorid)
        {
            var mentoridParameter = mentorid.HasValue ?
                new ObjectParameter("mentorid", mentorid) :
                new ObjectParameter("mentorid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getComment_Result>("getComment", mentoridParameter);
        }
    
        public virtual ObjectResult<getCommentByID_Result> getCommentByID(Nullable<int> internId, Nullable<int> projectId, Nullable<int> weekId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getCommentByID_Result>("getCommentByID", internIdParameter, projectIdParameter, weekIdParameter);
        }
    
        public virtual ObjectResult<GetFileDetails_Result> GetFileDetails(Nullable<int> internId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFileDetails_Result>("GetFileDetails", internIdParameter);
        }
    
        public virtual ObjectResult<getIntern_Result> getIntern()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getIntern_Result>("getIntern");
        }
    
        public virtual ObjectResult<getInternById_Result> getInternById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInternById_Result>("getInternById", idParameter);
        }
    
        public virtual ObjectResult<getInternByIdFromInternInfo_Result> getInternByIdFromInternInfo(Nullable<int> internId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInternByIdFromInternInfo_Result>("getInternByIdFromInternInfo", internIdParameter);
        }
    
        public virtual ObjectResult<getInternByIdFromtblInternInfo_Result> getInternByIdFromtblInternInfo(Nullable<int> internId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInternByIdFromtblInternInfo_Result>("getInternByIdFromtblInternInfo", internIdParameter);
        }
    
        public virtual ObjectResult<getInternByProjId_Result> getInternByProjId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getInternByProjId_Result>("getInternByProjId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetInternstoPublish(Nullable<int> projId, Nullable<int> prefId, Nullable<int> mentorId)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var prefIdParameter = prefId.HasValue ?
                new ObjectParameter("PrefId", prefId) :
                new ObjectParameter("PrefId", typeof(int));
    
            var mentorIdParameter = mentorId.HasValue ?
                new ObjectParameter("mentorId", mentorId) :
                new ObjectParameter("mentorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetInternstoPublish", projIdParameter, prefIdParameter, mentorIdParameter);
        }
    
        public virtual int GetMaxInternId(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMaxInternId", id);
        }
    
        public virtual int GetMaxMentorId(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMaxMentorId", id);
        }
    
        public virtual int GetMaxProjectId(ObjectParameter id)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetMaxProjectId", id);
        }
    
        public virtual ObjectResult<getMentor_Result> getMentor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMentor_Result>("getMentor");
        }
    
        public virtual ObjectResult<getMentorById_Result> getMentorById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMentorById_Result>("getMentorById", idParameter);
        }
    
        public virtual ObjectResult<getMentorByProjId_Result> getMentorByProjId()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getMentorByProjId_Result>("getMentorByProjId");
        }
    
        public virtual ObjectResult<Nullable<int>> GetMentortoNotify(Nullable<int> internId)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GetMentortoNotify", internIdParameter);
        }
    
        public virtual ObjectResult<getProjecTaskDetById_Result> getProjecTaskDetById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProjecTaskDetById_Result>("getProjecTaskDetById", idParameter);
        }
    
        public virtual ObjectResult<getProjectById_Result> getProjectById(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProjectById_Result>("getProjectById", idParameter);
        }
    
        public virtual ObjectResult<GetProjectByMentorId_Result> GetProjectByMentorId(Nullable<int> mentorId)
        {
            var mentorIdParameter = mentorId.HasValue ?
                new ObjectParameter("MentorId", mentorId) :
                new ObjectParameter("MentorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetProjectByMentorId_Result>("GetProjectByMentorId", mentorIdParameter);
        }
    
        public virtual ObjectResult<getProjects_Result> getProjects()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getProjects_Result>("getProjects");
        }
    
        public virtual ObjectResult<getRoles_Result> getRoles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getRoles_Result>("getRoles");
        }
    
        public virtual ObjectResult<getUnreadComment_Result> getUnreadComment(Nullable<int> mentorId)
        {
            var mentorIdParameter = mentorId.HasValue ?
                new ObjectParameter("MentorId", mentorId) :
                new ObjectParameter("MentorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUnreadComment_Result>("getUnreadComment", mentorIdParameter);
        }
    
        public virtual int InsertIntern(string internId, string fName, string mName, string lName, string address, string email, string contact, string qualification, Nullable<int> id)
        {
            var internIdParameter = internId != null ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(string));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var qualificationParameter = qualification != null ?
                new ObjectParameter("Qualification", qualification) :
                new ObjectParameter("Qualification", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertIntern", internIdParameter, fNameParameter, mNameParameter, lNameParameter, addressParameter, emailParameter, contactParameter, qualificationParameter, idParameter);
        }
    
        public virtual int InsertMentor(string mentorId, string fName, string mName, string lName, string address, string email, string contact, Nullable<int> id)
        {
            var mentorIdParameter = mentorId != null ?
                new ObjectParameter("MentorId", mentorId) :
                new ObjectParameter("MentorId", typeof(string));
    
            var fNameParameter = fName != null ?
                new ObjectParameter("FName", fName) :
                new ObjectParameter("FName", typeof(string));
    
            var mNameParameter = mName != null ?
                new ObjectParameter("MName", mName) :
                new ObjectParameter("MName", typeof(string));
    
            var lNameParameter = lName != null ?
                new ObjectParameter("LName", lName) :
                new ObjectParameter("LName", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var contactParameter = contact != null ?
                new ObjectParameter("Contact", contact) :
                new ObjectParameter("Contact", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertMentor", mentorIdParameter, fNameParameter, mNameParameter, lNameParameter, addressParameter, emailParameter, contactParameter, idParameter);
        }
    
        public virtual int InsertProject(string projectName, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> projId, Nullable<bool> wasDeleted)
        {
            var projectNameParameter = projectName != null ?
                new ObjectParameter("ProjectName", projectName) :
                new ObjectParameter("ProjectName", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var wasDeletedParameter = wasDeleted.HasValue ?
                new ObjectParameter("WasDeleted", wasDeleted) :
                new ObjectParameter("WasDeleted", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertProject", projectNameParameter, startDateParameter, endDateParameter, projIdParameter, wasDeletedParameter);
        }
    
        public virtual int InsertPublishedTask(Nullable<int> projId, Nullable<int> weekId, Nullable<int> taskId, string taskDes, Nullable<int> status, Nullable<int> internId)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            var taskIdParameter = taskId.HasValue ?
                new ObjectParameter("TaskId", taskId) :
                new ObjectParameter("TaskId", typeof(int));
    
            var taskDesParameter = taskDes != null ?
                new ObjectParameter("TaskDes", taskDes) :
                new ObjectParameter("TaskDes", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertPublishedTask", projIdParameter, weekIdParameter, taskIdParameter, taskDesParameter, statusParameter, internIdParameter);
        }
    
        public virtual int SaveAssignedTask(Nullable<int> projId, Nullable<int> prefId, Nullable<int> weekId, string taskDesc, string assignedBy)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var prefIdParameter = prefId.HasValue ?
                new ObjectParameter("prefId", prefId) :
                new ObjectParameter("prefId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("weekId", weekId) :
                new ObjectParameter("weekId", typeof(int));
    
            var taskDescParameter = taskDesc != null ?
                new ObjectParameter("TaskDesc", taskDesc) :
                new ObjectParameter("TaskDesc", typeof(string));
    
            var assignedByParameter = assignedBy != null ?
                new ObjectParameter("AssignedBy", assignedBy) :
                new ObjectParameter("AssignedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveAssignedTask", projIdParameter, prefIdParameter, weekIdParameter, taskDescParameter, assignedByParameter);
        }
    
        public virtual int SaveFeedback(Nullable<int> internId, Nullable<int> projectId, Nullable<int> weekId, string feedback)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            var feedbackParameter = feedback != null ?
                new ObjectParameter("feedback", feedback) :
                new ObjectParameter("feedback", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveFeedback", internIdParameter, projectIdParameter, weekIdParameter, feedbackParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_06c4c1e1_06c3_4d9d_ab7f_e04bf6bdec1c()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_06c4c1e1_06c3_4d9d_ab7f_e04bf6bdec1c");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_06cefa11_d88f_436b_90f1_8201e098c677()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_06cefa11_d88f_436b_90f1_8201e098c677");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_09b2dc64_7723_4509_8830_51ec763d987d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_09b2dc64_7723_4509_8830_51ec763d987d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_0b41d29b_1fe9_4d0f_8ad9_a02910dccba3()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_0b41d29b_1fe9_4d0f_8ad9_a02910dccba3");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_0e965a7f_8167_49e1_946a_841823b4fbe0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_0e965a7f_8167_49e1_946a_841823b4fbe0");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_0fb05f8b_1913_4584_ac75_46cb78e807c1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_0fb05f8b_1913_4584_ac75_46cb78e807c1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_11a68e49_b851_430d_aa7f_c3ff0a43554d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_11a68e49_b851_430d_aa7f_c3ff0a43554d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_13b30df6_4852_43fb_ad4c_fadc8135b660()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_13b30df6_4852_43fb_ad4c_fadc8135b660");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_18f19aee_8642_4ea5_ac96_18f65375f8db()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_18f19aee_8642_4ea5_ac96_18f65375f8db");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_1db29c25_92c7_4dc4_b152_fda2a75f216b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_1db29c25_92c7_4dc4_b152_fda2a75f216b");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_1efdd52c_1618_43c5_9bef_bcab29db99bc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_1efdd52c_1618_43c5_9bef_bcab29db99bc");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_2141d348_47ff_454b_9d6d_b183a7ca07ee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_2141d348_47ff_454b_9d6d_b183a7ca07ee");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_220e75f7_03b8_443c_bfc4_91bb14b5ab37()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_220e75f7_03b8_443c_bfc4_91bb14b5ab37");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_23637453_9a2e_4637_9cbf_a1393828a857()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_23637453_9a2e_4637_9cbf_a1393828a857");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_2479b760_3ce4_41bb_8d9b_9819be177838()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_2479b760_3ce4_41bb_8d9b_9819be177838");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_2c047e91_5746_4de8_a4f5_938770b933ef()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_2c047e91_5746_4de8_a4f5_938770b933ef");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_2cad817b_f2b6_47f6_b3d8_e62afcd61edc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_2cad817b_f2b6_47f6_b3d8_e62afcd61edc");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_30eff600_d33f_4e2f_b085_67fe984e0a35()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_30eff600_d33f_4e2f_b085_67fe984e0a35");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_361f1e55_0f61_4011_8936_90b113fefe5b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_361f1e55_0f61_4011_8936_90b113fefe5b");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_36784be2_8d3c_4c7f_8c12_344c1e62533b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_36784be2_8d3c_4c7f_8c12_344c1e62533b");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_381073a5_50a2_4d28_ae88_63c6fda34629()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_381073a5_50a2_4d28_ae88_63c6fda34629");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_383670ca_0541_4ce7_9c83_7a13c85a7b15()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_383670ca_0541_4ce7_9c83_7a13c85a7b15");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_3c600f7a_6557_4eb0_b20c_141b5d2e688c()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_3c600f7a_6557_4eb0_b20c_141b5d2e688c");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_3db12666_49ed_4d6f_843b_5abdc79aa322()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_3db12666_49ed_4d6f_843b_5abdc79aa322");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_45c92708_35e9_42a2_a1e9_3467be718556()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_45c92708_35e9_42a2_a1e9_3467be718556");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_4ad25557_377f_44ca_a2b4_a563f45e928d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_4ad25557_377f_44ca_a2b4_a563f45e928d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_4bdefe67_d0d9_45a9_b1f3_e67366dca0b6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_4bdefe67_d0d9_45a9_b1f3_e67366dca0b6");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_4c4c1455_2c0c_49f0_8812_776e3e798a93()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_4c4c1455_2c0c_49f0_8812_776e3e798a93");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_5109768f_639c_49dd_9384_ab422ff02eb2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_5109768f_639c_49dd_9384_ab422ff02eb2");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_52a278d2_8df0_4d0d_b78a_1419765960eb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_52a278d2_8df0_4d0d_b78a_1419765960eb");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_52b0a68c_cb5a_4e6e_9962_cf6d3b3d3373()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_52b0a68c_cb5a_4e6e_9962_cf6d3b3d3373");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_534c902e_05a2_45de_805e_00a77d38954f()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_534c902e_05a2_45de_805e_00a77d38954f");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_53812da4_7884_4fdd_928f_453b6a56d803()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_53812da4_7884_4fdd_928f_453b6a56d803");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_5d31bbe4_21cc_4bcf_a28b_2e22e9e18b79()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_5d31bbe4_21cc_4bcf_a28b_2e22e9e18b79");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_5e1a9c2d_4ace_4cda_ac21_15b89944a397()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_5e1a9c2d_4ace_4cda_ac21_15b89944a397");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6317b339_f9f4_4209_9c11_7b980c252884()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6317b339_f9f4_4209_9c11_7b980c252884");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_66b3e139_408c_496a_b53c_65d4ffc4e144()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_66b3e139_408c_496a_b53c_65d4ffc4e144");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_67807f65_ba7d_4435_88f7_1d1a77d2a674()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_67807f65_ba7d_4435_88f7_1d1a77d2a674");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6a6d3dca_1d12_4ec9_9fdc_eae72fd117e1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6a6d3dca_1d12_4ec9_9fdc_eae72fd117e1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6cad0f2d_3501_47f6_a128_eb1bbda78a53()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6cad0f2d_3501_47f6_a128_eb1bbda78a53");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6e2afd48_3d7d_4b5f_a03f_9f5ab9291106()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6e2afd48_3d7d_4b5f_a03f_9f5ab9291106");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6ec44410_116d_46de_aedc_4307551e9e25()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6ec44410_116d_46de_aedc_4307551e9e25");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6ef07e06_dc9c_406c_8350_5a5f840d395e()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6ef07e06_dc9c_406c_8350_5a5f840d395e");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_6f278629_8635_4fc7_8833_568151173533()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_6f278629_8635_4fc7_8833_568151173533");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_74f1804a_ae8f_4cf4_9914_6074f4d79724()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_74f1804a_ae8f_4cf4_9914_6074f4d79724");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_77cb68e5_8871_4406_9f18_7aeff168f5c0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_77cb68e5_8871_4406_9f18_7aeff168f5c0");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_787085a2_d524_4e59_a0bc_129eeae3093f()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_787085a2_d524_4e59_a0bc_129eeae3093f");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_78bfb9c9_73e0_4436_aa7b_4eb3128049e1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_78bfb9c9_73e0_4436_aa7b_4eb3128049e1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_7bd115cf_5146_4fa6_9807_578815e51469()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_7bd115cf_5146_4fa6_9807_578815e51469");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_7db8b543_348c_480e_b810_341a8bcf8941()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_7db8b543_348c_480e_b810_341a8bcf8941");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_7eb1f0fc_d6c0_4c14_bb96_a3ee615ee766()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_7eb1f0fc_d6c0_4c14_bb96_a3ee615ee766");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_81f1b54a_ee20_4002_846a_62e3dd1e6725()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_81f1b54a_ee20_4002_846a_62e3dd1e6725");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_84877353_e157_49f5_a427_964adb3d88cb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_84877353_e157_49f5_a427_964adb3d88cb");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_882ef240_87b4_48df_af71_ac9215fd8760()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_882ef240_87b4_48df_af71_ac9215fd8760");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_8a05056e_6424_4d69_8d8a_0bc302ba82dd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_8a05056e_6424_4d69_8d8a_0bc302ba82dd");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_8f671638_b199_47dd_984c_f79789b8941b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_8f671638_b199_47dd_984c_f79789b8941b");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_91bed3a1_03e5_4bee_96ce_33ca73263d93()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_91bed3a1_03e5_4bee_96ce_33ca73263d93");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_9bb1dec6_a602_4134_91d8_06802291549d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_9bb1dec6_a602_4134_91d8_06802291549d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_a327705c_d55f_4495_94aa_10bf1ddfb290()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_a327705c_d55f_4495_94aa_10bf1ddfb290");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_ab58305e_93f0_4e51_bed8_f7c6dc21cfe1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_ab58305e_93f0_4e51_bed8_f7c6dc21cfe1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_ac49ac4e_5412_4a4f_a314_2322aa99d3d2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_ac49ac4e_5412_4a4f_a314_2322aa99d3d2");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_acedb4b4_4ed9_4eed_9a25_2c18e8a5e726()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_acedb4b4_4ed9_4eed_9a25_2c18e8a5e726");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_ae74030b_325b_42c4_bb14_561f82b3bc86()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_ae74030b_325b_42c4_bb14_561f82b3bc86");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_ae942c8d_3870_4ac5_84a4_61d82af23862()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_ae942c8d_3870_4ac5_84a4_61d82af23862");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_afbec480_77e3_410b_85c0_369d95b77c4a()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_afbec480_77e3_410b_85c0_369d95b77c4a");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_b25cf83e_ec42_4f0c_9878_c40bf21239ea()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_b25cf83e_ec42_4f0c_9878_c40bf21239ea");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_b41ebfa2_8fd4_4816_af50_503a43afa8d1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_b41ebfa2_8fd4_4816_af50_503a43afa8d1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_b55a842e_df7f_43aa_b2bf_90fe414c5764()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_b55a842e_df7f_43aa_b2bf_90fe414c5764");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_b9bf5e6b_dc62_493c_95e5_2fea72629ce2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_b9bf5e6b_dc62_493c_95e5_2fea72629ce2");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_beeeeb18_78db_4630_a85a_70365537ff64()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_beeeeb18_78db_4630_a85a_70365537ff64");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_c1909edc_6042_45d8_8ac3_758268f3df88()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_c1909edc_6042_45d8_8ac3_758268f3df88");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_c40299ee_beef_4a10_99d1_4b46697892b8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_c40299ee_beef_4a10_99d1_4b46697892b8");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_c8d3ad3a_b326_478a_bd62_4f41f6c3fea2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_c8d3ad3a_b326_478a_bd62_4f41f6c3fea2");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_caafb9c3_30fc_499e_9d33_7de68f9be7eb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_caafb9c3_30fc_499e_9d33_7de68f9be7eb");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_cb572faf_3060_4629_b5a2_cac85cf197b0()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_cb572faf_3060_4629_b5a2_cac85cf197b0");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_d067ee2b_b387_4f79_94b5_e6c9d768e33d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_d067ee2b_b387_4f79_94b5_e6c9d768e33d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_d57c8466_d10b_4ee8_b460_b3c27bb9d667()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_d57c8466_d10b_4ee8_b460_b3c27bb9d667");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_d7fdd80a_c2c4_4a02_9062_e893cf6f7470()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_d7fdd80a_c2c4_4a02_9062_e893cf6f7470");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_d92525bd_b44b_4b34_8694_2fb1c1bdaf89()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_d92525bd_b44b_4b34_8694_2fb1c1bdaf89");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_d9eb2050_744a_4071_a2c0_7f2d233864a6()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_d9eb2050_744a_4071_a2c0_7f2d233864a6");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_da665adb_cc57_4143_a84d_4d802deb7400()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_da665adb_cc57_4143_a84d_4d802deb7400");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_dc3c1fa0_48d2_42a5_bb5d_eddfc738429d()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_dc3c1fa0_48d2_42a5_bb5d_eddfc738429d");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_dcbfbaa3_e359_43b8_a053_73b0b3ccc911()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_dcbfbaa3_e359_43b8_a053_73b0b3ccc911");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_dd77b5c5_2917_40e5_8083_377e92927723()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_dd77b5c5_2917_40e5_8083_377e92927723");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_df792a4c_8102_4fa1_9dcc_b7b85336c854()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_df792a4c_8102_4fa1_9dcc_b7b85336c854");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e0852d0e_5a04_4a1c_b5ed_689d81d246da()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e0852d0e_5a04_4a1c_b5ed_689d81d246da");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e2ffffec_1755_4317_b6ee_ee164db3f910()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e2ffffec_1755_4317_b6ee_ee164db3f910");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e476c13e_370e_40c9_97e6_949042fa7f13()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e476c13e_370e_40c9_97e6_949042fa7f13");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e5308cf5_7031_44b2_b485_0b66e7c3f19b()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e5308cf5_7031_44b2_b485_0b66e7c3f19b");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_e7c4c891_c9da_4e64_833d_5e03ff509dd8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_e7c4c891_c9da_4e64_833d_5e03ff509dd8");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f09ddc0a_e606_4282_9ed9_aa5e484e6c63()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f09ddc0a_e606_4282_9ed9_aa5e484e6c63");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f33bb672_d6ae_47fb_a8c4_bb9956e22487()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f33bb672_d6ae_47fb_a8c4_bb9956e22487");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f40206df_e46f_491e_a1a3_b66d6226d52e()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f40206df_e46f_491e_a1a3_b66d6226d52e");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f4f780f6_1fc4_4009_8409_e020a0ba0feb()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f4f780f6_1fc4_4009_8409_e020a0ba0feb");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f584042d_3b88_4562_88b4_a91ad868c0a1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f584042d_3b88_4562_88b4_a91ad868c0a1");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f5fdf379_4d81_4e4c_8ffe_431c28bf8ca8()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f5fdf379_4d81_4e4c_8ffe_431c28bf8ca8");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_f61c0aba_2966_44e4_b0a0_efd158a5a7ff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_f61c0aba_2966_44e4_b0a0_efd158a5a7ff");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_fbd2c2a2_39fb_4b6b_9b86_dd872b6dc41c()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_fbd2c2a2_39fb_4b6b_9b86_dd872b6dc41c");
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> SqlQueryNotificationStoredProcedure_ff04da2d_86ca_4c27_b6e2_782c72700107()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("SqlQueryNotificationStoredProcedure_ff04da2d_86ca_4c27_b6e2_782c72700107");
        }
    
        public virtual int UpdateAssignedTask(Nullable<int> projId, Nullable<int> prefId, Nullable<int> weekId, string taskDesc, string assignedBy, Nullable<int> taskId)
        {
            var projIdParameter = projId.HasValue ?
                new ObjectParameter("ProjId", projId) :
                new ObjectParameter("ProjId", typeof(int));
    
            var prefIdParameter = prefId.HasValue ?
                new ObjectParameter("prefId", prefId) :
                new ObjectParameter("prefId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("weekId", weekId) :
                new ObjectParameter("weekId", typeof(int));
    
            var taskDescParameter = taskDesc != null ?
                new ObjectParameter("TaskDesc", taskDesc) :
                new ObjectParameter("TaskDesc", typeof(string));
    
            var assignedByParameter = assignedBy != null ?
                new ObjectParameter("AssignedBy", assignedBy) :
                new ObjectParameter("AssignedBy", typeof(string));
    
            var taskIdParameter = taskId.HasValue ?
                new ObjectParameter("TaskId", taskId) :
                new ObjectParameter("TaskId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateAssignedTask", projIdParameter, prefIdParameter, weekIdParameter, taskDescParameter, assignedByParameter, taskIdParameter);
        }
    
        public virtual int UpdateComment(string comment, Nullable<int> internId, Nullable<System.DateTime> dateTime, Nullable<int> projectId, Nullable<int> weekId)
        {
            var commentParameter = comment != null ?
                new ObjectParameter("Comment", comment) :
                new ObjectParameter("Comment", typeof(string));
    
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("InternId", internId) :
                new ObjectParameter("InternId", typeof(int));
    
            var dateTimeParameter = dateTime.HasValue ?
                new ObjectParameter("DateTime", dateTime) :
                new ObjectParameter("DateTime", typeof(System.DateTime));
    
            var projectIdParameter = projectId.HasValue ?
                new ObjectParameter("ProjectId", projectId) :
                new ObjectParameter("ProjectId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("WeekId", weekId) :
                new ObjectParameter("WeekId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateComment", commentParameter, internIdParameter, dateTimeParameter, projectIdParameter, weekIdParameter);
        }
    
        public virtual int UpdateIsPublished(Nullable<int> taskId)
        {
            var taskIdParameter = taskId.HasValue ?
                new ObjectParameter("taskId", taskId) :
                new ObjectParameter("taskId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateIsPublished", taskIdParameter);
        }
    
        public virtual int UpdateIsRead(Nullable<int> cmtId)
        {
            var cmtIdParameter = cmtId.HasValue ?
                new ObjectParameter("cmtId", cmtId) :
                new ObjectParameter("cmtId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateIsRead", cmtIdParameter);
        }
    
        public virtual int UpdatePreference(Nullable<int> internId, Nullable<int> prefId, string projrole)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("internId", internId) :
                new ObjectParameter("internId", typeof(int));
    
            var prefIdParameter = prefId.HasValue ?
                new ObjectParameter("prefId", prefId) :
                new ObjectParameter("prefId", typeof(int));
    
            var projroleParameter = projrole != null ?
                new ObjectParameter("projrole", projrole) :
                new ObjectParameter("projrole", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePreference", internIdParameter, prefIdParameter, projroleParameter);
        }
    
        public virtual int updateTaskStatus(Nullable<int> internId, Nullable<int> taskId, Nullable<int> weekId, Nullable<int> status)
        {
            var internIdParameter = internId.HasValue ?
                new ObjectParameter("internId", internId) :
                new ObjectParameter("internId", typeof(int));
    
            var taskIdParameter = taskId.HasValue ?
                new ObjectParameter("taskId", taskId) :
                new ObjectParameter("taskId", typeof(int));
    
            var weekIdParameter = weekId.HasValue ?
                new ObjectParameter("weekId", weekId) :
                new ObjectParameter("weekId", typeof(int));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("updateTaskStatus", internIdParameter, taskIdParameter, weekIdParameter, statusParameter);
        }
    
        public virtual int UpdateUser(Nullable<int> userId, string password)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", userIdParameter, passwordParameter);
        }
    
        public virtual ObjectResult<verifyLogin_Result> verifyLogin(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verifyLogin_Result>("verifyLogin", usernameParameter, passwordParameter);
        }
    }
}
