//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedTask
    {
        public int TaskId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> PrefId { get; set; }
        public Nullable<int> WeekId { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string AssignedBy { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    }
}
