//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProj_Task
    {
        public int ProjId { get; set; }
        public int WeekId { get; set; }
        public int TaskId { get; set; }
        public string TaskDes { get; set; }
        public Nullable<int> Status { get; set; }
        public int InternId { get; set; }
    }
}
